/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Total paramaeters:  11171266
Trainable parameters:  11171266
/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:60: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(
Traceback (most recent call last):                                                                     
  File "/mnt/32mins/gender_detection/ekstep-language-identification/train.py", line 92, in <module>
    trained_model = train(1, num_epochs, device, np.inf, loaders, model, optimizer, criterion, use_cuda, checkpoint_path,
  File "/mnt/32mins/gender_detection/ekstep-language-identification/utils/training.py", line 130, in train
    for batch_idx, (data, target) in tqdm(enumerate(loaders['train']), total=len(loaders['train']), leave=False):
  File "/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
    return self._process_data(data)
  File "/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
    data.reraise()
  File "/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/librosa/core/audio.py", line 176, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/librosa/core/audio.py", line 209, in __soundfile_load
    context = sf.SoundFile(path)
  File "/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening '/mnt/32mins/gender_detection/datasets/kannada/wavs/6192449487764834_chunk_15_enhanced.wav': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/32mins/gender_detection/ekstep-language-identification/loaders/data_loader.py", line 19, in __getitem__
    spec = utils.load_data(audio_link, mode=self.mode)[np.newaxis, ...]
  File "/mnt/32mins/gender_detection/ekstep-language-identification/utils/utils.py", line 23, in load_data
    audio_data = load_wav(filepath, sr=sr, min_dur_sec=min_dur_sec)
  File "/mnt/32mins/gender_detection/ekstep-language-identification/utils/utils.py", line 6, in load_wav
    audio_data, fs = librosa.load(audio_filepath, sr=16000)
  File "/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/librosa/core/audio.py", line 184, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/librosa/util/decorators.py", line 59, in __wrapper
    return func(*args, **kwargs)
  File "/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/librosa/core/audio.py", line 240, in __audioread_load
    reader = audioread.audio_open(path)
  File "/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/audioread/__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "/mnt/32mins/language_detection/venv/lib/python3.10/site-packages/audioread/rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/32mins/gender_detection/datasets/kannada/wavs/6192449487764834_chunk_15_enhanced.wav'
